USE [master]
GO

/****** Object:  Database [ServicesTekus]    Script Date: 21/02/2022 10:50:15 p.m. ******/
CREATE DATABASE [ServicesTekus] ON  PRIMARY 
( NAME = N'ServicesTekus', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\ServicesTekus.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ServicesTekus_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\ServicesTekus_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ServicesTekus].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ServicesTekus] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ServicesTekus] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ServicesTekus] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ServicesTekus] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ServicesTekus] SET ARITHABORT OFF 
GO

ALTER DATABASE [ServicesTekus] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ServicesTekus] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ServicesTekus] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ServicesTekus] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ServicesTekus] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ServicesTekus] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ServicesTekus] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ServicesTekus] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ServicesTekus] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ServicesTekus] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ServicesTekus] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ServicesTekus] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ServicesTekus] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ServicesTekus] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ServicesTekus] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ServicesTekus] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ServicesTekus] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ServicesTekus] SET  MULTI_USER 
GO

ALTER DATABASE [ServicesTekus] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ServicesTekus] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ServicesTekus] SET  READ_WRITE 
GO

