
/****** Object:  Table [ISS].[PROVIDER]    Script Date: 21/02/2022 10:47:44 p.m. ******/

CREATE TABLE [ISS].[PROVIDER](
	[ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[NIT] [nvarchar](50) NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[EMAIL] [nvarchar](50) NULL,
 CONSTRAINT [PK_PROVIDER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

