

/****** Object:  Table [ISS].[SERVICE]    Script Date: 21/02/2022 10:49:14 p.m. ******/


CREATE TABLE [ISS].[SERVICE](
	[ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[PRICE_PER_HOUR] [numeric](18, 0) NOT NULL,
	[ID_PROVIDER] [numeric](18, 0) NOT NULL,
 CONSTRAINT [PK_SERVICE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [ISS].[SERVICE]  WITH CHECK ADD  CONSTRAINT [FK_SERVICE_PROVIDER] FOREIGN KEY([ID_PROVIDER])
REFERENCES [ISS].[PROVIDER] ([ID])
GO

ALTER TABLE [ISS].[SERVICE] CHECK CONSTRAINT [FK_SERVICE_PROVIDER]
GO

