
/****** Object:  Table [ISS].[DYNAMIC_FIELDS]    Script Date: 21/02/2022 10:48:23 p.m. ******/

CREATE TABLE [ISS].[DYNAMIC_FIELDS](
	[ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[VALUE] [nvarchar](50) NOT NULL,
	[ID_PROVIDER] [numeric](18, 0) NOT NULL,
	[ENABLE] [bit] NOT NULL,
 CONSTRAINT [PK_DYNAMIC_FIELDS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [ISS].[DYNAMIC_FIELDS] ADD  CONSTRAINT [DF_DYNAMIC_FIELDS_ENABLE]  DEFAULT ((1)) FOR [ENABLE]
GO

ALTER TABLE [ISS].[DYNAMIC_FIELDS]  WITH CHECK ADD  CONSTRAINT [FK_DYNAMIC_FIELDS_PROVIDER] FOREIGN KEY([ID_PROVIDER])
REFERENCES [ISS].[PROVIDER] ([ID])
GO

ALTER TABLE [ISS].[DYNAMIC_FIELDS] CHECK CONSTRAINT [FK_DYNAMIC_FIELDS_PROVIDER]
GO

