

/****** Object:  Table [ISS].[SERVICE_COUNTRY]    Script Date: 21/02/2022 10:49:41 p.m. ******/


CREATE TABLE [ISS].[SERVICE_COUNTRY](
	[ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[ID_SERVICE] [numeric](18, 0) NOT NULL,
	[ID_COUNTRY] [numeric](18, 0) NOT NULL,
	[ENABLE] [bit] NOT NULL,
 CONSTRAINT [PK_SERVICE_COUNTRY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [ISS].[SERVICE_COUNTRY] ADD  CONSTRAINT [DF_SERVICE_COUNTRY_ENABLE]  DEFAULT ((1)) FOR [ENABLE]
GO

ALTER TABLE [ISS].[SERVICE_COUNTRY]  WITH CHECK ADD  CONSTRAINT [FK_SERVICE_COUNTRY_COUNTRY] FOREIGN KEY([ID_COUNTRY])
REFERENCES [ISS].[COUNTRY] ([ID])
GO

ALTER TABLE [ISS].[SERVICE_COUNTRY] CHECK CONSTRAINT [FK_SERVICE_COUNTRY_COUNTRY]
GO

ALTER TABLE [ISS].[SERVICE_COUNTRY]  WITH CHECK ADD  CONSTRAINT [FK_SERVICE_COUNTRY_SERVICE] FOREIGN KEY([ID_SERVICE])
REFERENCES [ISS].[SERVICE] ([ID])
GO

ALTER TABLE [ISS].[SERVICE_COUNTRY] CHECK CONSTRAINT [FK_SERVICE_COUNTRY_SERVICE]
GO

