
USE [ServicesTekus]
GO




INSERT INTO [ISS].[COUNTRY]  ([NAME])
     VALUES    ('COLOMBIA')



INSERT INTO [ISS].[COUNTRY]  ([NAME])
     VALUES    ('PERU')

INSERT INTO [ISS].[COUNTRY]  ([NAME])
     VALUES    ('MEXICO')

INSERT INTO [ISS].[COUNTRY]  ([NAME])
     VALUES    ('EEUU')

INSERT INTO [ISS].[COUNTRY]  ([NAME])
     VALUES    ('PANAMA')

INSERT INTO [ISS].[COUNTRY]  ([NAME])
     VALUES    ('CHILE')

INSERT INTO [ISS].[COUNTRY]  ([NAME])
     VALUES    ('ECUADOR')

INSERT INTO [ISS].[COUNTRY]  ([NAME])
     VALUES    ('CANADA')

INSERT INTO [ISS].[COUNTRY]  ([NAME])
     VALUES    ('ARGENTINA')

INSERT INTO [ISS].[COUNTRY]  ([NAME])
     VALUES    ('ESPAÑA')

GO

